
"""Jinja2-based project structure generator."""

from __future__ import annotations

from pathlib import Path
import shutil

from jinja2 import Environment, FileSystemLoader
import questionary

from .config import ProjectConfig

TEMPLATE_STRUCTURE: dict[str, list[str]] = {
    "single_agent": [
        "agents/",
        "tools/",
        "memory/",
        "api/",
        "agents/agent.py",
        "tools/sample_tool.py",
        "memory/state.py",
        "api/main.py",
        "main.py",
        "config.py",
        ".env.example",
        "requirements.txt",
        "README.md",
    ],
    "multi_agent": [
        "agents/",
        "agents/workers/",
        "tools/",
        "memory/",
        "api/",
        "agents/supervisor.py",
        "agents/workers/researcher.py",
        "agents/workers/writer.py",
        "tools/search_tool.py",
        "memory/state.py",
        "api/main.py",
        "main.py",
        "config.py",
        ".env.example",
        "requirements.txt",
        "README.md",
    ],
    "rag_agent": [
        "rag/",
        "agents/",
        "tools/",
        "memory/",
        "api/",
        "rag/vectorstore.py",
        "rag/ingest.py",
        "rag/retriever.py",
        "agents/rag_agent.py",
        "tools/retriever_tool.py",
        "memory/state.py",
        "api/main.py",
        "main.py",
        "sample_docs/",
        "sample_docs/sample.txt",
        "config.py",
        ".env.example",
        "requirements.txt",
        "README.md",
    ],
}

SHARED_TEMPLATE_MAP: dict[str, str] = {
    "config.py": "shared/config.py.j2",
    ".env.example": "shared/.env.example.j2",
    "requirements.txt": "shared/requirements.txt.j2",
    "README.md": "shared/README.md.j2",
}

PLACEHOLDER_FILES: dict[str, str] = {
    "README.md": "# {{ project_name }}\n\nGenerated by create-agent-app.\n",
}


class GenerationAbortedError(RuntimeError):
    """Raised when the user aborts project generation."""


def render_template(template_path: Path, context: dict[str, object]) -> str:
    """Render a Jinja2 template file with context."""
    templates_root = template_path.parents[1]
    relative_template = template_path.relative_to(templates_root).as_posix()
    env = Environment(
        loader=FileSystemLoader(str(templates_root)),
        keep_trailing_newline=True,
        autoescape=False,
    )
    return env.get_template(relative_template).render(**context)


def write_file(path: Path, content: str, overwrite: bool = False) -> None:
    """Write file content with overwrite protection."""
    if path.exists() and not overwrite:
        raise FileExistsError(f"Refusing to overwrite existing file: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def copy_static_file(src: Path, dest: Path, overwrite: bool = False) -> None:
    """Copy a non-templated static file with overwrite protection."""
    if dest.exists() and not overwrite:
        raise FileExistsError(f"Refusing to overwrite existing file: {dest}")
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dest)


def create_project_structure(config: ProjectConfig, overwrite: bool = False) -> Path:
    """Create directories and files based on the selected template."""
    if config.template not in TEMPLATE_STRUCTURE:
        supported = ", ".join(sorted(TEMPLATE_STRUCTURE))
        raise ValueError(f"Unknown template '{config.template}'. Supported templates: {supported}")

    target_root = config.output_dir
    templates_root = Path(__file__).parent / "templates"
    context = config.to_dict()

    if target_root.exists() and not overwrite:
        should_overwrite = questionary.confirm(
            f"Target directory '{target_root}' already exists. Overwrite scaffold files?",
            default=False,
        ).ask()
        if should_overwrite is None or not should_overwrite:
            raise GenerationAbortedError(
                f"Generation aborted. Directory '{target_root}' was not modified."
            )
        overwrite = True

    for item in TEMPLATE_STRUCTURE[config.template]:
        destination = target_root / item

        if item.endswith("/"):
            destination.mkdir(parents=True, exist_ok=True)
            continue

        template_specific_j2 = templates_root / config.template / f"{item}.j2"
        if template_specific_j2.exists() and template_specific_j2.is_file():
            rendered = render_template(template_specific_j2, context)
            write_file(destination, rendered, overwrite=overwrite)
            continue

        if item in SHARED_TEMPLATE_MAP:
            template_file = templates_root / SHARED_TEMPLATE_MAP[item]
            rendered = render_template(template_file, context)
            write_file(destination, rendered, overwrite=overwrite)
            continue

        # Template-specific static assets (if present) are copied verbatim.
        static_source = templates_root / config.template / item
        if static_source.exists() and static_source.is_file():
            copy_static_file(static_source, destination, overwrite=overwrite)
            continue

        placeholder_template = PLACEHOLDER_FILES.get(item, "")
        if "{{" in placeholder_template:
            env = Environment(autoescape=False)
            content = env.from_string(placeholder_template).render(**context)
        else:
            content = placeholder_template
        write_file(destination, content, overwrite=overwrite)

    return target_root
